-- DSA Visualized — cloud schema, version 1.
--
-- Shape carried over from the desktop store (`crates/dsa-store`): profiles own
-- progress, favourites and playlists, and a progress row exists only once a
-- problem has been touched — "to do" is the absence of a row, so an untouched
-- 287-problem catalogue costs nothing per profile.
--
-- New for the cloud: accounts own profiles (Netflix-style, a handful each),
-- sessions are server-side and revocable, and every run is a submission.
--
-- Ids are UUIDv7, generated by the application: time-ordered, so inserts land
-- at the right-hand edge of the B-tree instead of scattering across it.
-- Problem slugs are plain text, not foreign keys: content is files shipped in
-- the image, not rows, and a slug renamed by a content release must not be able
-- to fail a write.

-- ─────────────────────────────────────────────────────────────────────────────
-- Accounts
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE users (
    id                  uuid        PRIMARY KEY,
    email               text        NOT NULL,
    -- Lower-cased and trimmed. Uniqueness is on this, so "Sam@X.com" and
    -- "sam@x.com" are one account.
    email_normalized    text        NOT NULL UNIQUE,
    email_verified_at   timestamptz,
    -- NULL for an account that has only ever signed in through OAuth.
    password_hash       text,
    display_name        text        NOT NULL,
    role                text        NOT NULL DEFAULT 'user'
                        CHECK (role IN ('user', 'admin')),
    -- Denormalized from `subscriptions` so an entitlement check is one column
    -- on a row that is already loaded with the session.
    plan                text        NOT NULL DEFAULT 'free'
                        CHECK (plan IN ('free', 'pro')),
    plan_renews_at      timestamptz,
    stripe_customer_id  text        UNIQUE,
    -- IANA name. Streaks and the activity heatmap count *local* days.
    timezone            text        NOT NULL DEFAULT 'UTC',
    -- Per-account brute-force brake, on top of the per-IP rate limit.
    failed_logins       integer     NOT NULL DEFAULT 0,
    locked_until        timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    last_login_at       timestamptz
);

CREATE TABLE oauth_identities (
    provider            text        NOT NULL,
    provider_user_id    text        NOT NULL,
    user_id             uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    email               text,
    created_at          timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (provider, provider_user_id)
);

CREATE INDEX oauth_identities_user ON oauth_identities (user_id);

-- The cookie carries a random 256-bit token; only its SHA-256 is stored, so a
-- leaked database dump contains no usable sessions.
CREATE TABLE sessions (
    id                  uuid        PRIMARY KEY,
    user_id             uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash          bytea       NOT NULL UNIQUE,
    created_at          timestamptz NOT NULL DEFAULT now(),
    last_seen_at        timestamptz NOT NULL DEFAULT now(),
    expires_at          timestamptz NOT NULL,
    user_agent          text,
    ip                  text,
    revoked_at          timestamptz
);

CREATE INDEX sessions_user_live ON sessions (user_id) WHERE revoked_at IS NULL;
CREATE INDEX sessions_expiry ON sessions (expires_at);

-- Single-use links sent by email. Same hashing rule as sessions.
CREATE TABLE auth_tokens (
    token_hash          bytea       PRIMARY KEY,
    user_id             uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    purpose             text        NOT NULL
                        CHECK (purpose IN ('verify_email', 'reset_password')),
    created_at          timestamptz NOT NULL DEFAULT now(),
    expires_at          timestamptz NOT NULL,
    used_at             timestamptz
);

CREATE INDEX auth_tokens_user ON auth_tokens (user_id, purpose);

-- ─────────────────────────────────────────────────────────────────────────────
-- Profiles and progress (the desktop store, per account)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE profiles (
    id                  uuid        PRIMARY KEY,
    user_id             uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name                text        NOT NULL,
    -- One glyph from the avatar set, and a `#rrggbb` from the palette.
    avatar              text        NOT NULL,
    color               text        NOT NULL,
    -- UI preferences (language, tier, speed, filters, watch pins …): the
    -- desktop's `Settings`, synced across devices instead of kept per machine.
    settings            jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT now(),
    last_seen_at        timestamptz NOT NULL DEFAULT now()
);

-- The picker shows nothing but the name, so two "Sam"s cannot be told apart.
CREATE UNIQUE INDEX profiles_user_name ON profiles (user_id, lower(name));

CREATE TABLE progress (
    profile_id          uuid        NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
    slug                text        NOT NULL,
    status              text        NOT NULL DEFAULT 'todo'
                        CHECK (status IN ('todo', 'attempted', 'solved')),
    favourite           boolean     NOT NULL DEFAULT false,
    -- How many times Run or the tests were pressed on it.
    attempts            integer     NOT NULL DEFAULT 0,
    solved_at           timestamptz,
    updated_at          timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (profile_id, slug)
);

CREATE INDEX progress_profile_status ON progress (profile_id, status);

CREATE TABLE playlists (
    id                  uuid        PRIMARY KEY,
    profile_id          uuid        NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
    name                text        NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX playlists_profile_name ON playlists (profile_id, lower(name));

CREATE TABLE playlist_items (
    playlist_id         uuid        NOT NULL REFERENCES playlists (id) ON DELETE CASCADE,
    slug                text        NOT NULL,
    added_at            timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (playlist_id, slug)
);

-- The practice editor's contents, autosaved per problem and language, so work
-- in progress follows the user from laptop to desktop.
CREATE TABLE drafts (
    profile_id          uuid        NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
    slug                text        NOT NULL,
    lang                text        NOT NULL,
    code                text        NOT NULL,
    updated_at          timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (profile_id, slug, lang)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Runs
-- ─────────────────────────────────────────────────────────────────────────────

-- Every Run and every test sweep. The largest table by far; the two indexes
-- serve the only two ways it is read (a profile's history, and a profile's
-- history on one problem). At scale this is the table to partition by month.
CREATE TABLE submissions (
    id                  uuid        PRIMARY KEY,
    profile_id          uuid        NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
    user_id             uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    slug                text        NOT NULL,
    lang                text        NOT NULL,
    kind                text        NOT NULL CHECK (kind IN ('run', 'test')),
    mode                text        NOT NULL CHECK (mode IN ('solution', 'program')),
    code                text        NOT NULL,
    -- passed | failed | compile_error | runtime_error | timeout | error | ok
    status              text        NOT NULL,
    passed              integer     NOT NULL DEFAULT 0,
    total               integer     NOT NULL DEFAULT 0,
    duration_ms         integer     NOT NULL DEFAULT 0,
    -- Per-case detail, already truncated to what the UI shows.
    result              jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX submissions_profile_time ON submissions (profile_id, created_at DESC);
CREATE INDEX submissions_profile_slug_time ON submissions (profile_id, slug, created_at DESC);
CREATE INDEX submissions_user_time ON submissions (user_id, created_at DESC);

-- A daily roll-up per profile: what the streak counter and the activity
-- heatmap read, so neither has to scan submissions.
CREATE TABLE activity_days (
    profile_id          uuid        NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
    day                 date        NOT NULL,
    runs                integer     NOT NULL DEFAULT 0,
    solved              integer     NOT NULL DEFAULT 0,
    PRIMARY KEY (profile_id, day)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Metering and billing
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE ai_usage (
    user_id             uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    day                 date        NOT NULL,
    requests            integer     NOT NULL DEFAULT 0,
    input_tokens        bigint      NOT NULL DEFAULT 0,
    output_tokens       bigint      NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, day)
);

CREATE TABLE subscriptions (
    -- Stripe's subscription id.
    id                  text        PRIMARY KEY,
    user_id             uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status              text        NOT NULL,
    price_id            text,
    current_period_end  timestamptz,
    cancel_at_period_end boolean    NOT NULL DEFAULT false,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX subscriptions_user ON subscriptions (user_id);

-- Stripe retries webhooks; this makes handling one twice a no-op.
CREATE TABLE stripe_events (
    id                  text        PRIMARY KEY,
    type                text        NOT NULL,
    received_at         timestamptz NOT NULL DEFAULT now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Security audit trail
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE audit_events (
    id                  bigserial   PRIMARY KEY,
    user_id             uuid        REFERENCES users (id) ON DELETE SET NULL,
    kind                text        NOT NULL,
    ip                  text,
    meta                jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX audit_events_user_time ON audit_events (user_id, created_at DESC);
