// The ✏ Practice tab — crates/dsa-app/src/practice.rs.
//
// Columns, left to right: the statement, the editor, STDIN/OUTPUT/TESTS and
// (when open) the AI assistant; the outer two toggle from the toolbar. Below
// 1100px the side columns become tabs beside the editor, below 700px the
// editor is one of the tabs too.
//
// Buffers follow the desktop exactly. Each language has a *solution* buffer —
// seeded from the saved draft or the starter, autosaved as the draft — and a
// *full program* view that is the solution assembled into the harness. That
// view is derived until the user edits it; from then on it is theirs, runs
// verbatim (`mode: program`) and is only regenerated by "reset code".

import { useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react'
import { useLocation } from 'react-router'
import clsx from 'clsx'
import { nextParam } from '@/app/guards'
import { useMeta, useRun } from '@/api/hooks'
import type { Problem, ProblemSource, RunKind, RunRequest, RunResult, Uuid } from '@/api/types'
import { AssistantPanel } from '@/features/assistant/AssistantPanel'
import { CodeEditor } from '@/features/editor'
import { useSettings } from '@/state/settings'
import { PageSpinner, Seg, useToast, type SegOption } from '@/ui'
import type { LangInfo } from '../shared/langs'
import { Splitter, useColumnWidth, type ColumnSpec } from '../shared/Splitter'
import ui from '../shared/ui.module.css'
import { COMPACT_QUERY, PHONE_QUERY, useMediaQuery } from '../shared/useMediaQuery'
import { assemble } from './assemble'
import { compiled, defaultStdin, logHint, runContext } from './format'
import { IoPanel } from './IoPanel'
import { QuestionPanel } from './QuestionPanel'
import { describeRunError, type RunNotice } from './runNotice'
import { useDraftStore } from './useDraftStore'
import styles from './Practice.module.css'

type View = 'solution' | 'full'
type Pane = 'code' | 'question' | 'io' | 'ai'

// The desktop's default widths and `width_range`s.
const QUESTION: ColumnSpec = { id: 'practice.question', initial: 340, min: 240, max: 520 }
const IO: ColumnSpec = { id: 'practice.io', initial: 320, min: 240, max: 520 }
const AI: ColumnSpec = { id: 'practice.ai', initial: 380, min: 300, max: 560 }
const SIDE: ColumnSpec = { id: 'practice.side', initial: 340, min: 260, max: 520 }

const VIEW_OPTIONS: SegOption<View>[] = [
  { value: 'solution', label: 'solution', title: 'Your solution — the function(s) you write' },
  { value: 'full', label: 'full program', title: 'The whole runnable program your solution is spliced into' },
]

export interface PracticeTabProps {
  problem: Problem
  source: ProblemSource
  lang: LangInfo
  pid: Uuid | null
  guest: boolean
  solved: boolean
  hidden: boolean
  visualizeHref: string | null
  /** A test sweep just ticked the problem off. */
  onSolved: () => void
}

/** Epoch ms, re-rendering every second while `active` — for cooldown countdowns. */
function useNow(active: boolean): number {
  const [now, setNow] = useState(() => Date.now())
  useEffect(() => {
    if (!active) return
    setNow(Date.now())
    const t = setInterval(() => setNow(Date.now()), 1000)
    return () => clearInterval(t)
  }, [active])
  return now
}

export function PracticeTab({
  problem,
  source,
  lang,
  pid,
  guest,
  solved,
  hidden,
  visualizeHref,
  onSolved,
}: PracticeTabProps) {
  const { settings, update } = useSettings()
  const meta = useMeta()
  const toast = useToast()
  const location = useLocation()
  const run = useRun(pid)
  const slug = problem.slug

  const langIds = useMemo(() => problem.sources.map((s) => s.lang), [problem.sources])
  const drafts = useDraftStore({ pid, slug, langs: langIds, limit: meta.data?.limits.draft_bytes })

  const [view, setView] = useState<View>('solution')
  const [solutions, setSolutions] = useState<Record<string, string>>({})
  /** Full-program buffers the user has taken over, by language. */
  const [owned, setOwned] = useState<Record<string, string>>({})
  const [stdin, setStdin] = useState(() => defaultStdin(problem))
  const [runResult, setRunResult] = useState<RunResult | null>(null)
  const [testResult, setTestResult] = useState<RunResult | null>(null)
  const [notice, setNotice] = useState<RunNotice | null>(null)
  const [solvedNow, setSolvedNow] = useState(false)

  // A language switch is a different program with different output, so the
  // previous results no longer describe what is on screen.
  const [resultsLang, setResultsLang] = useState(lang.id)
  if (resultsLang !== lang.id) {
    setResultsLang(lang.id)
    setRunResult(null)
    setTestResult(null)
    setNotice(null)
    setSolvedNow(false)
  }

  // What the editor opens on: the pack's blanked reference, or — for a source
  // with nothing to blank — the harness, since a whole program beats an empty editor.
  const starter = source.starter.trim() ? source.starter : (source.harness ?? '')
  const solution = solutions[lang.id] ?? drafts.initial(lang.id) ?? starter
  const ownedFull = owned[lang.id]
  const full = useMemo(
    () => ownedFull ?? assemble(solution, source.code, source.harness),
    [ownedFull, solution, source.code, source.harness],
  )

  const running = run.isPending
  const runnerUp = meta.data?.features.runner !== false
  // In the solution view there has to be something to wrap the solution in;
  // without it the compiler would complain about a missing `main` — a message
  // about the harness, shown to someone looking at their own code.
  const wrapped = view === 'full' || source.harness !== null
  const cooldownUntil = notice?.kind === 'error' ? (notice.retryAt ?? 0) : 0
  const now = useNow(cooldownUntil > Date.now())
  const cooldown = Math.max(0, Math.ceil((cooldownUntil - now) / 1000))
  const canPress = drafts.ready && runnerUp && lang.runnable && wrapped && !running && cooldown === 0

  const langRef = useRef(lang.id)
  useLayoutEffect(() => {
    langRef.current = lang.id
  })

  const start = (kind: RunKind) => {
    if (!canPress || (kind === 'test' && problem.tests.length === 0)) return
    if (guest) return setNotice({ kind: 'signin' })
    if (!pid) return setNotice({ kind: 'profile' })
    const program = view === 'full' ? owned[lang.id] : undefined
    const req: RunRequest =
      program !== undefined
        ? { slug, lang: lang.id, code: program, mode: 'program', kind }
        : { slug, lang: lang.id, code: solution, mode: 'solution', kind }
    if (kind === 'run') req.stdin = stdin
    setNotice(null)
    if (kind === 'run') setRunResult(null)
    else {
      setTestResult(null)
      setSolvedNow(false)
    }
    const wasSolved = solved
    run.mutate(req, {
      onSuccess: (res) => {
        if (res.lang !== langRef.current) return
        if (res.kind === 'run') return setRunResult(res)
        setTestResult(res)
        // The server ticks the problem off when every case passes; say so,
        // once, and only when this sweep is what did it.
        if (res.status === 'passed' && res.progress.status === 'solved' && !wasSolved) {
          setSolvedNow(true)
          onSolved()
          toast.success(`Solved — all ${res.total} tests pass. ${problem.title} is ticked off.`)
        }
      },
      onError: (e) => setNotice(describeRunError(e)),
    })
  }

  // Ctrl/Cmd+Enter and Ctrl/Cmd+' from anywhere on the tab, not only the
  // editor (which handles them itself and marks the event handled).
  const startRef = useRef(start)
  useLayoutEffect(() => {
    startRef.current = start
  })
  useEffect(() => {
    if (hidden) return
    const onKey = (e: KeyboardEvent) => {
      if (e.defaultPrevented || !(e.ctrlKey || e.metaKey) || e.altKey || e.shiftKey) return
      if (e.target instanceof Element && e.target.closest('[aria-modal="true"]')) return
      if (e.key === 'Enter') startRef.current('run')
      else if (e.key === "'") startRef.current('test')
      else return
      e.preventDefault()
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [hidden])

  const editSolution = (code: string) => {
    setSolutions((s) => ({ ...s, [lang.id]: code }))
    drafts.save(lang.id, code)
  }

  const onEdit = (code: string) => {
    if (view === 'solution') editSolution(code)
    else setOwned((o) => ({ ...o, [lang.id]: code }))
  }

  const resetCode = () => {
    if (view === 'full') {
      setOwned((o) => {
        const next = { ...o }
        delete next[lang.id]
        return next
      })
    } else {
      setSolutions((s) => ({ ...s, [lang.id]: starter }))
      drafts.discard(lang.id)
    }
    setRunResult(null)
  }

  // The AI's accepted fix replaces the solution, like the desktop's review.
  const applyCode = (code: string) => {
    setView('solution')
    editSolution(code)
  }

  const context = useMemo(() => runContext(runResult, testResult), [runResult, testResult])

  // ── layout ────────────────────────────────────────────────────────────────
  const compact = useMediaQuery(COMPACT_QUERY)
  const phone = useMediaQuery(PHONE_QUERY)
  const [qWidth, setQWidth] = useColumnWidth(QUESTION)
  const [ioWidth, setIoWidth] = useColumnWidth(IO)
  const [aiWidth, setAiWidth] = useColumnWidth(AI)
  const [sideWidth, setSideWidth] = useColumnWidth(SIDE)
  const aiEnabled = meta.data?.features.ai.enabled !== false
  const showQuestion = settings.show_question
  const showAi = aiEnabled && settings.ai_open

  const [pane, setPane] = useState<Pane>('io')
  const paneOptions: SegOption<Pane>[] = [
    ...(phone ? [{ value: 'code' as const, label: 'code' }] : []),
    ...(showQuestion ? [{ value: 'question' as const, label: '📄 question' }] : []),
    { value: 'io', label: 'run & tests' },
    ...(showAi ? [{ value: 'ai' as const, label: '💬 AI' }] : []),
  ]
  const shownPane = paneOptions.some((o) => o.value === pane) ? pane : paneOptions[0].value

  const toggleQuestion = () => {
    if (!showQuestion) setPane('question')
    update({ show_question: !showQuestion })
  }
  const toggleAi = () => {
    if (!settings.ai_open) setPane('ai')
    update({ ai_open: !settings.ai_open })
  }

  const runner = !runnerUp
    ? { text: `${lang.label} · runner offline`, cls: styles.bad, title: 'Code execution is not available right now.' }
    : !lang.runnable
      ? {
          text: `${lang.label} · not runnable`,
          cls: styles.bad,
          title: `${lang.label} can be read and visualized here, but not run.`,
        }
      : {
          text: `${lang.label} · cloud toolchain`,
          cls: styles.good,
          title: `Runs on a real ${lang.label} toolchain in an isolated sandbox.`,
        }

  const next = nextParam(location)
  const announcement = running
    ? 'Running…'
    : notice
      ? notice.kind === 'error'
        ? notice.text
        : notice.kind === 'signin'
          ? 'Sign in to run code.'
          : 'Pick a profile to run code.'
      : testResult
        ? `Tests finished: ${testResult.passed} of ${testResult.total} passed.`
        : runResult
          ? `Run finished: ${runResult.status === 'error' ? 'the runner failed' : !compiled(runResult) ? 'compile error' : `exit code ${runResult.exit_code ?? 'none'}`}.`
          : ''

  const question = <QuestionPanel problem={problem} visualizeHref={visualizeHref} />
  const io = (
    <IoPanel
      problem={problem}
      langLabel={lang.label}
      stdin={stdin}
      onStdin={setStdin}
      running={running}
      runResult={runResult}
      testResult={testResult}
      notice={notice}
      cooldown={cooldown}
      next={next}
      solvedNow={solvedNow}
    />
  )
  const ai = showAi && (
    <AssistantPanel
      problem={problem}
      lang={lang.id}
      code={solution}
      runContext={context}
      onApplyCode={applyCode}
      onClose={() => update({ ai_open: false })}
    />
  )
  const editor = (
    <div className={styles.editorFrame}>
      {drafts.ready ? (
        <CodeEditor
          className={styles.editor}
          docKey={`${lang.id}:${view}`}
          value={view === 'solution' ? solution : full}
          syntax={lang.syntax}
          onChange={onEdit}
          onRun={() => start('run')}
          onTest={() => start('test')}
          label={`${view === 'solution' ? 'Your solution' : 'Full program'} (${lang.label})`}
        />
      ) : (
        <PageSpinner label="Loading your saved code…" />
      )}
    </div>
  )

  const sidePanes = (
    <>
      <Seg
        small
        className={ui.paneTabs}
        value={shownPane}
        options={paneOptions}
        onChange={setPane}
        aria-label="Panel"
      />
      {showQuestion && (
        <div className={styles.pane} hidden={shownPane !== 'question'}>
          {question}
        </div>
      )}
      <div className={styles.pane} hidden={shownPane !== 'io'}>
        {io}
      </div>
      {ai && (
        <div className={clsx(styles.pane, styles.aiPane)} hidden={shownPane !== 'ai'}>
          {ai}
        </div>
      )}
    </>
  )

  return (
    <div className={styles.practice} hidden={hidden}>
      <div className={ui.toolbar} role="toolbar" aria-label="Practice">
        <button
          type="button"
          className={ui.apply}
          disabled={!canPress}
          onClick={() => start('run')}
          title="Run with the STDIN on the right (Ctrl+Enter)"
        >
          {running ? '⏳ running…' : '▶ Run'}
        </button>
        <button
          type="button"
          className="mini-btn"
          disabled={!canPress || problem.tests.length === 0}
          onClick={() => start('test')}
          title="Run every test case (Ctrl+')"
        >
          ✔ run tests
        </button>
        <Seg value={view} options={VIEW_OPTIONS} onChange={setView} aria-label="Editor shows" />
        <button
          type="button"
          className="mini-btn"
          onClick={resetCode}
          title={
            view === 'full' ? 'Regenerate the full program from your solution' : 'Reset to the empty starter skeleton'
          }
        >
          reset code
        </button>
        {wrapped ? (
          <code className={styles.logHint} title="Print debug lines — they show up in OUTPUT">
            {logHint(lang.id)}
          </code>
        ) : (
          <>
            <span
              className={styles.warn}
              title="This pack ships no main() for this language, and its inputs do not line up with the solution's parameters closely enough to derive one. Switch to “full program” to write the whole thing, including main()."
            >
              ⚠ no runnable harness for this problem
            </span>
            <button type="button" className="mini-btn" onClick={() => setView('full')}>
              → full program
            </button>
          </>
        )}
        <span className={ui.spacer} />
        <span className={clsx(styles.runner, runner.cls)} title={runner.title}>
          {runner.text}
        </span>
        <button
          type="button"
          className="mini-btn"
          aria-pressed={showQuestion}
          onClick={toggleQuestion}
          title="Show / hide the problem statement"
        >
          📄 question
        </button>
        {aiEnabled && (
          <button
            type="button"
            className="mini-btn"
            aria-pressed={settings.ai_open}
            onClick={toggleAi}
            title="AI assistant — interview, guide or fix mode"
          >
            💬 AI assist
          </button>
        )}
      </div>
      <p className="visually-hidden" role="status" aria-live="polite">
        {announcement}
      </p>

      {!compact ? (
        <div className={styles.columns}>
          {showQuestion && (
            <>
              <section key="question" className={styles.side} style={{ flexBasis: qWidth }}>
                {question}
              </section>
              <Splitter
                key="question-split"
                spec={QUESTION}
                width={qWidth}
                onResize={setQWidth}
                side="left"
                label="Resize the problem statement"
              />
            </>
          )}
          <section key="main" className={styles.main} aria-label="Editor">
            {editor}
          </section>
          <Splitter
            key="io-split"
            spec={IO}
            width={ioWidth}
            onResize={setIoWidth}
            side="right"
            label="Resize the input and output column"
          />
          <section key="io" className={styles.side} style={{ flexBasis: ioWidth }}>
            {io}
          </section>
          {ai && (
            <>
              <Splitter
                key="ai-split"
                spec={AI}
                width={aiWidth}
                onResize={setAiWidth}
                side="right"
                label="Resize the AI assistant"
              />
              <section key="ai" className={clsx(styles.side, styles.aiPane)} style={{ flexBasis: aiWidth }}>
                {ai}
              </section>
            </>
          )}
        </div>
      ) : (
        <div className={clsx(styles.columns, phone && styles.stacked)}>
          <section
            key="main"
            className={styles.main}
            aria-label="Editor"
            hidden={phone && shownPane !== 'code'}
          >
            {editor}
          </section>
          {!phone && (
            <Splitter
              key="side-split"
              spec={SIDE}
              width={sideWidth}
              onResize={setSideWidth}
              side="right"
              label="Resize the side panel"
            />
          )}
          <section key="side" className={styles.side} style={phone ? undefined : { flexBasis: sideWidth }}>
            {sidePanes}
          </section>
        </div>
      )}
    </div>
  )
}
